services:
  flask:
    build: ./flask
    container_name: flask
    restart: always
    expose:
      - 8080
    depends_on:
      - mongodb
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - 8003:80
  mongodb:
    image: mongo:4.2.0
    container_name: mongodb
    volumes:
      - mongo_data:/data/db
    restart: always
volumes:
  mongo_data: